export const AUTHEN = {
  STUDENT_HOME: "STUDENT_HOME",
  STUDENT_LOGIN: "STUDENT_LOGIN",
  STUDENT_VERIFY: "STUDENT_VERIFY",
  LECTURE_HOME: "LECTURE_HOME",
  LECTURE_LOGIN: "LECTURE_LOGIN",
  LECTURE_VERIFY: "LECTURE_VERIFY",
  RESET_PASSWORD: "RESET_PASSWORD"
};