export const TOKEN = {
  RESET_PASSWORD: "RESET_PASSWORD_TOKEN",
  STUDENT_LOGIN: "STUDENT_LOGIN_TOKEN",
  LECTURE_LOGIN: "LECTURE_LOGIN_TOKEN"
};

export const ACCOUNT_ID = "ACCOUNT_ID"

export const SOCKET = {
  CREATE_POST_NOTI: "CREATE_POST_NOTI"
}