export const FETCH_OTP = {
  REQUEST: "FETCH_OTP",
  SUCCESS: "FETCH_OTP_SUCCESS",
  FAILURE: "FETCH_OTP_FAILURE"
};

export const FETCH_OTP_RESEND = "FETCH_OTP_RESEND";
export const FETCH_VERIFY = "FETCH_VERIFY";
