export const FETCH_OTP = "FETCH_OTP";
export const FETCH_IS_SEND = "FETCH_IS_SEND";
export const FETCH_OTP_FORGOT_PASSWORD = "FETCH_OTP_FORGOT_PASSWORD";
export const FETCH_TOKEN_RESET_PASSWORD = "FETCH_TOKEN_RESET_PASSWORD";

