export const CHECK_FAB_PROGRESS = {
  REQUEST: "loading -> CHECK_FAB_PROGRESS_REQUEST",
  SUCCESS: "loading -> CHECK_FAB_PROGRESS_SUCCESS",
  FAILURE: "loading -> CHECK_FAB_PROGRESS_FAILURE"
};

export const CHECK_FETCH_CLASSROOMS = {
  REQUEST: "loading -> CHECK_FETCH_CLASSROOMS_REQUEST",
  SUCCESS: "loading -> CHECK_FETCH_CLASSROOMS_SUCCESS",
  FAILURE: "loading -> CHECK_FETCH_CLASSROOMS_FAILURE"
};

export const CHECK_FETCH_POSTS = {
  REQUEST: "loading -> CHECK_FETCH_POSTS_REQUEST",
  SUCCESS: "loading -> CHECK_FETCH_POSTS_SUCCESS",
  FAILURE: "loading -> CHECK_FETCH_POSTS_FAILURE"
};

export const CHECK_FETCH_STUDENT_LIST = {
  REQUEST: "loading -> CHECK_FETCH_STUDENT_LIST_REQUEST",
  SUCCESS: "loading -> CHECK_FETCH_STUDENT_LIST_SUCCESS",
  FAILURE: "loading -> CHECK_FETCH_STUDENT_LIST_FAILURE"
};

export const CHECK_FETCH_CLASSROOM_INFO = {
  REQUEST: "loading -> CHECK_FETCH_CLASSROOM_INFO_REQUEST",
  SUCCESS: "loading -> CHECK_FETCH_CLASSROOM_INFO_SUCCESS",
  FAILURE: "loading -> CHECK_FETCH_CLASSROOM_INFO_FAILURE"
};