export const SEND_OTP = "SEND_OTP";
export const CHECK_SEND = "CHECK_SEND";
export const SEND_OTP_FORGOT_PASSWORD = "SEND_OTP_FORGOT_PASSWORD";
export const SEND_RESET_PASSWORD_TOKEN = "SEND_RESET_PASSWORD_TOKEN";

