export const FETCH_STUDENT_SIGN_IN = {
  REQUEST: "FETCH_STUDENT_SIGN_IN",
  SUCCESS: "FETCH_STUDENT_SIGN_IN_SUCCESS",
  FAILURE: "FETCH_STUDENT_SIGN_IN_FAILURE"
};

export const FETCH_STUDENT_SIGN_UP = {
  REQUEST: "FETCH_STUDENT_SIGN_UP",
  SUCCESS: "FETCH_STUDENT_SIGN_UP_SUCCESS",
  FAILURE: "FETCH_STUDENT_SIGN_UP_FAILURE"
};
